(** This GCode was generated by ReplicatorG 0037 **)
(*  using Skeinforge (50)  *)
(*  for a Dual headed The Replicator  *)
(*  on 2013/01/03 20:55:44 (-0500) *)
(**** start.gcode for The Replicator, dual head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
G10 P1 X0 Y0 Z0 (Designate T0 Offset)
G10 P2 X33 Y0 Z0 (Designate T1 Offset)
M109 S110 T1 (set HBP temperature)
M104 S220 T1 (set extruder temperature) (temp updated by printOMatic)
G55 (Recall offset cooridinate system)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T1 (wait for toolhead, and HBP to reach temperature)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T1
G0 X-110.5 Y-74 (Position Nozzle)
G0 Z0.2      (Position Height)
M108 R4.0    (Set Extruder Speed)
M101         (Start Extruder)
G4 P1500     (Create Anchor)
(**** end of start.gcode ****)
(<format> skeinforge gcode </format>)
(<version> 12.03.14 </version>)
(<created> 13.01.03|20:55 </created>)
(<extruderInitialization>)
(<craftTypeName> extrusion </craftTypeName>)
M105
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
(<layerThickness> 0.27 </layerThickness>)
(<infillWidth> 0.4 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.27 </layerHeight>)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 999.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.9 </objectFirstLayerFeedRateInfillMultiplier>)
(<operatingFeedRatePerSecond> 40.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.8 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 40.0 </operatingFlowRate>)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 55.0 </travelFeedRatePerSecond>)
(<edgeWidth> 0.4 </edgeWidth>)
(<perimeterWidth> 0.4 </perimeterWidth>)
(<profileName> ABS </profileName>)
(<settings>)
(<setting> alteration Activate_Alteration True </setting>)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> comb Activate_Comb True </setting>)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning False </setting>)
(<setting> cool Turn_Fan_Off_at_Ending False </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.82 </setting>)
(<setting> dimension Filament_Packing_Density_(ratio): 0.85 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 1.0 </setting>)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
(<setting> export Add_Export_Suffix False </setting>)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
(<setting> export gcode_small False </setting>)
(<setting> export File_Extension: gcode </setting>)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 1 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 1 </setting>)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 1 </setting>)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
(<setting> fill Grid_Hexagonal True </setting>)
(<setting> fill Grid_Rectangular False </setting>)
(<setting> fill Line False </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 0.1 </setting>)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 60.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
(<setting> home Activate_Home True </setting>)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
(<setting> raft Activate_Raft True </setting>)
(<setting> raft Add_Raft,_Elevate_Nozzle,_Orbit: False </setting>)
(<setting> raft Base_Feed_Rate_Multiplier_(ratio): 0.75 </setting>)
(<setting> raft Base_Flow_Rate_Multiplier_(ratio): 0.6 </setting>)
(<setting> raft Base_Infill_Density_(ratio): 0.3 </setting>)
(<setting> raft Base_Layer_Thickness_over_Layer_Thickness: 2.2 </setting>)
(<setting> raft Base_Layers_(integer): 1 </setting>)
(<setting> raft Base_Nozzle_Lift_over_Base_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Initial_Circling: False </setting>)
(<setting> raft Infill_Overhang_over_Extrusion_Width_(ratio): 0.1 </setting>)
(<setting> raft Interface_Feed_Rate_Multiplier_(ratio): 1.5 </setting>)
(<setting> raft Interface_Flow_Rate_Multiplier_(ratio): 0.7 </setting>)
(<setting> raft Interface_Infill_Density_(ratio): 0.4 </setting>)
(<setting> raft Interface_Layer_Thickness_over_Layer_Thickness: 1.8 </setting>)
(<setting> raft Interface_Layers_(integer): 2 </setting>)
(<setting> raft Interface_Nozzle_Lift_over_Interface_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Name_of_Support_End_File: support_end.gcode </setting>)
(<setting> raft Name_of_Support_Start_File: support_start.gcode </setting>)
(<setting> raft Operating_Nozzle_Lift_over_Layer_Thickness_(ratio): 0.0 </setting>)
(<setting> raft Raft_Additional_Margin_over_Length_(%): 2.5 </setting>)
(<setting> raft Raft_Margin_(mm): 2.5 </setting>)
(<setting> raft Support_Cross_Hatch False </setting>)
(<setting> raft Support_Flow_Rate_over_Operating_Flow_Rate_(ratio): 0.7 </setting>)
(<setting> raft Support_Gap_over_Perimeter_Extrusion_Width_(ratio): 0.005 </setting>)
(<setting> raft None True </setting>)
(<setting> raft Empty_Layers_Only False </setting>)
(<setting> raft Everywhere False </setting>)
(<setting> raft Exterior_Only False </setting>)
(<setting> raft Support_Minimum_Angle_(degrees): 45.0 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 40.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 40.0 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.8 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 999.0 </setting>)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 55.0 </setting>)
(</settings>)
(<timeStampPreface> 20130103_205542 </timeStampPreface>)
(<procedureName> carve </procedureName>)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
(<procedureName> speed </procedureName>)
(<procedureName> raft </procedureName>)
(<procedureName> jitter </procedureName>)
(<procedureName> comb </procedureName>)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
(<crafting>)
;M113 S1.0
;M108 R18.0
M73 P16 (display progress)
(<layer> 2.135 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X4.357 Y7.809 Z2.135 </boundaryPoint>)
(<boundaryPoint> X7.723 Y7.809 Z2.135 </boundaryPoint>)
(<boundaryPoint> X7.723 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X8.58 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X8.58 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X7.723 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X7.723 Y8.763 Z2.135 </boundaryPoint>)
(<boundaryPoint> X4.357 Y8.763 Z2.135 </boundaryPoint>)
(<boundaryPoint> X4.357 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X3.5 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X3.5 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X4.357 Y4.0 Z2.135 </boundaryPoint>)
(<edge> outer )
G1 X3.7 Y4.21 Z2.13 F3300.0
G1 F1200.0
G1 E1.0
G1 F3300.0
M101
G1 X3.7 Y4.2 Z2.13 F1080.0 E1.0
G1 X4.16 Y4.2 Z2.13 F1080.0 E1.023
G1 X4.16 Y8.01 Z2.13 F1080.0 E1.209
G1 X7.92 Y8.01 Z2.13 F1080.0 E1.393
G1 X7.92 Y4.2 Z2.13 F1080.0 E1.579
G1 X8.38 Y4.2 Z2.13 F1080.0 E1.601
G1 X8.38 Y11.88 Z2.13 F1080.0 E1.976
G1 X7.92 Y11.88 Z2.13 F1080.0 E1.998
G1 X7.92 Y8.56 Z2.13 F1080.0 E2.16
G1 X4.16 Y8.56 Z2.13 F1080.0 E2.344
G1 X4.16 Y11.88 Z2.13 F1080.0 E2.506
G1 X3.7 Y11.88 Z2.13 F1080.0 E2.529
G1 X3.7 Y4.21 Z2.13 F1080.0 E2.904
G1 F1200.0
G1 E1.904
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X4.157 Y8.009 Z2.135 </infillPoint>)
(<infillPoint> X7.923 Y8.009 Z2.135 </infillPoint>)
(<infillPoint> X7.923 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X8.38 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X8.38 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X7.923 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X7.923 Y8.563 Z2.135 </infillPoint>)
(<infillPoint> X4.157 Y8.563 Z2.135 </infillPoint>)
(<infillPoint> X4.157 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X3.7 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X3.7 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X4.157 Y4.2 Z2.135 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X10.071 Y4.392 Z2.135 </boundaryPoint>)
(<boundaryPoint> X11.556 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X13.065 Y4.45 Z2.135 </boundaryPoint>)
(<boundaryPoint> X13.86 Y5.615 Z2.135 </boundaryPoint>)
(<boundaryPoint> X14.08 Y7.55 Z2.135 </boundaryPoint>)
(<boundaryPoint> X14.08 Y12.219 Z2.135 </boundaryPoint>)
(<boundaryPoint> X13.226 Y12.219 Z2.135 </boundaryPoint>)
(<boundaryPoint> X13.226 Y7.556 Z2.135 </boundaryPoint>)
(<boundaryPoint> X12.825 Y5.5 Z2.135 </boundaryPoint>)
(<boundaryPoint> X11.481 Y4.965 Z2.135 </boundaryPoint>)
(<boundaryPoint> X10.549 Y5.235 Z2.135 </boundaryPoint>)
(<boundaryPoint> X10.011 Y6.004 Z2.135 </boundaryPoint>)
(<boundaryPoint> X9.855 Y7.556 Z2.135 </boundaryPoint>)
(<boundaryPoint> X9.855 Y12.219 Z2.135 </boundaryPoint>)
(<boundaryPoint> X9.0 Y12.219 Z2.135 </boundaryPoint>)
(<boundaryPoint> X9.0 Y7.55 Z2.135 </boundaryPoint>)
(<boundaryPoint> X9.247 Y5.524 Z2.135 </boundaryPoint>)
(<edge> outer )
G1 X4.16 Y8.01 Z2.13 F3300.0
G1 X7.92 Y8.01 Z2.13 F3300.0
G1 X7.78 Y5.56 Z2.13 F3300.0
G1 X11.03 Y4.37 Z2.13 F3300.0
G1 X9.44 Y5.61 Z2.13 F3300.0
G1 F1200.0
G1 E2.904
G1 F3300.0
M101
G1 X9.44 Y5.6 Z2.13 F1080.0 E2.904
G1 X10.19 Y4.57 Z2.13 F1080.0 E2.966
G1 X11.55 Y4.21 Z2.13 F1080.0 E3.035
G1 X12.94 Y4.62 Z2.13 F1080.0 E3.106
G1 X13.67 Y5.69 Z2.13 F1080.0 E3.169
G1 X13.88 Y7.56 Z2.13 F1080.0 E3.261
G1 X13.88 Y12.02 Z2.13 F1080.0 E3.479
G1 X13.43 Y12.02 Z2.13 F1080.0 E3.501
G1 X13.43 Y7.54 Z2.13 F1080.0 E3.72
G1 X13.0 Y5.36 Z2.13 F1080.0 E3.828
G1 X11.49 Y4.75 Z2.13 F1080.0 E3.908
G1 X10.43 Y5.06 Z2.13 F1080.0 E3.962
G1 X9.82 Y5.93 Z2.13 F1080.0 E4.014
G1 X9.65 Y7.55 Z2.13 F1080.0 E4.093
G1 X9.65 Y12.02 Z2.13 F1080.0 E4.311
G1 X9.2 Y12.02 Z2.13 F1080.0 E4.333
G1 X9.2 Y7.56 Z2.13 F1080.0 E4.551
G1 X9.44 Y5.61 Z2.13 F1080.0 E4.647
G1 F1200.0
G1 E3.647
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X10.191 Y4.567 Z2.135 </infillPoint>)
(<infillPoint> X11.553 Y4.208 Z2.135 </infillPoint>)
(<infillPoint> X12.94 Y4.621 Z2.135 </infillPoint>)
(<infillPoint> X13.667 Y5.687 Z2.135 </infillPoint>)
(<infillPoint> X13.88 Y7.561 Z2.135 </infillPoint>)
(<infillPoint> X13.88 Y12.019 Z2.135 </infillPoint>)
(<infillPoint> X13.426 Y12.019 Z2.135 </infillPoint>)
(<infillPoint> X13.426 Y7.537 Z2.135 </infillPoint>)
(<infillPoint> X13.0 Y5.355 Z2.135 </infillPoint>)
(<infillPoint> X11.491 Y4.754 Z2.135 </infillPoint>)
(<infillPoint> X10.426 Y5.063 Z2.135 </infillPoint>)
(<infillPoint> X9.817 Y5.932 Z2.135 </infillPoint>)
(<infillPoint> X9.655 Y7.546 Z2.135 </infillPoint>)
(<infillPoint> X9.655 Y12.019 Z2.135 </infillPoint>)
(<infillPoint> X9.2 Y12.019 Z2.135 </infillPoint>)
(<infillPoint> X9.2 Y7.562 Z2.135 </infillPoint>)
(<infillPoint> X9.439 Y5.6 Z2.135 </infillPoint>)
(</infillBoundary>)
;M108 R32.0
G1 X10.33 Y4.93 Z2.13 F3300.0
G1 X12.8 Y4.91 Z2.13 F3300.0
G1 F1200.0
G1 E4.647
G1 F3300.0
M101
G1 X12.8 Y4.97 Z2.13 F2160.0 E4.65
G1 X12.4 Y4.81 Z2.13 F2160.0 E4.669
G1 X12.4 Y4.75 Z2.13 F2160.0 E4.671
G1 X12.0 Y4.65 Z2.13 F2160.0 E4.689
G1 X12.0 Y4.63 Z2.13 F2160.0 E4.69
G1 F1200.0
G1 E3.69
G1 F2160.0
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X15.319 Y9.955 Z2.135 </boundaryPoint>)
(<boundaryPoint> X15.357 Y10.061 Z2.135 </boundaryPoint>)
(<boundaryPoint> X15.422 Y10.077 Z2.135 </boundaryPoint>)
(<boundaryPoint> X15.505 Y10.002 Z2.135 </boundaryPoint>)
(<boundaryPoint> X18.705 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X19.581 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X19.581 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X18.762 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X18.762 Y6.132 Z2.135 </boundaryPoint>)
(<boundaryPoint> X18.724 Y6.026 Z2.135 </boundaryPoint>)
(<boundaryPoint> X18.659 Y6.01 Z2.135 </boundaryPoint>)
(<boundaryPoint> X18.576 Y6.085 Z2.135 </boundaryPoint>)
(<boundaryPoint> X15.376 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X14.501 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X14.501 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X15.319 Y4.0 Z2.135 </boundaryPoint>)
(<edge> outer )
;M108 R18.0
G1 X13.88 Y5.92 Z2.13 F3300.0
G1 X15.3 Y5.92 Z2.13 F3300.0
G1 X14.7 Y4.64 Z2.13 F3300.0
G1 F1200.0
G1 E4.69
G1 F3300.0
M101
G1 X14.7 Y4.63 Z2.13 F1080.0 E4.69
G1 X14.7 Y4.2 Z2.13 F1080.0 E4.712
G1 X15.12 Y4.2 Z2.13 F1080.0 E4.732
G1 X15.12 Y9.99 Z2.13 F1080.0 E5.015
G1 X15.2 Y10.23 Z2.13 F1080.0 E5.027
G1 X15.48 Y10.3 Z2.13 F1080.0 E5.041
G1 X15.66 Y10.13 Z2.13 F1080.0 E5.053
G1 X18.82 Y4.2 Z2.13 F1080.0 E5.381
G1 X19.38 Y4.2 Z2.13 F1080.0 E5.408
G1 X19.38 Y11.88 Z2.13 F1080.0 E5.784
G1 X18.96 Y11.88 Z2.13 F1080.0 E5.804
G1 X18.96 Y6.1 Z2.13 F1080.0 E6.087
G1 X18.88 Y5.86 Z2.13 F1080.0 E6.099
G1 X18.6 Y5.79 Z2.13 F1080.0 E6.113
G1 X18.42 Y5.96 Z2.13 F1080.0 E6.125
G1 X15.26 Y11.88 Z2.13 F1080.0 E6.453
G1 X14.7 Y11.88 Z2.13 F1080.0 E6.48
G1 X14.7 Y4.64 Z2.13 F1080.0 E6.834
G1 F1200.0
G1 E5.834
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X15.119 Y9.99 Z2.135 </infillPoint>)
(<infillPoint> X15.205 Y10.23 Z2.135 </infillPoint>)
(<infillPoint> X15.477 Y10.297 Z2.135 </infillPoint>)
(<infillPoint> X15.665 Y10.127 Z2.135 </infillPoint>)
(<infillPoint> X18.825 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X19.381 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X19.381 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X18.962 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X18.962 Y6.097 Z2.135 </infillPoint>)
(<infillPoint> X18.876 Y5.857 Z2.135 </infillPoint>)
(<infillPoint> X18.604 Y5.79 Z2.135 </infillPoint>)
(<infillPoint> X18.416 Y5.96 Z2.135 </infillPoint>)
(<infillPoint> X15.256 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X14.701 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X14.701 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X15.119 Y4.2 Z2.135 </infillPoint>)
(</infillBoundary>)
;M108 R32.0
G1 X14.92 Y4.78 Z2.13 F3300.0
G1 X15.71 Y9.89 Z2.13 F3300.0
G1 X15.51 Y10.42 Z2.13 F3300.0
G1 X18.33 Y5.55 Z2.13 F3300.0
G1 X18.8 Y5.55 Z2.13 F3300.0
G1 F1200.0
G1 E6.834
G1 F3300.0
M101
G1 X18.8 Y4.84 Z2.13 F2160.0 E6.864
G1 F1200.0
G1 E5.864
G1 F2160.0
M103
G1 X15.2 Y10.52 Z2.13 F3300.0
G1 F1200.0
G1 E6.864
G1 F3300.0
M101
G1 X15.2 Y11.39 Z2.13 F2160.0 E6.902
G1 F1200.0
G1 E5.902
G1 F2160.0
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X21.995 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X22.796 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X22.796 Y11.127 Z2.135 </boundaryPoint>)
(<boundaryPoint> X24.798 Y11.127 Z2.135 </boundaryPoint>)
(<boundaryPoint> X24.798 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X20.0 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X20.0 Y11.127 Z2.135 </boundaryPoint>)
(<boundaryPoint> X21.995 Y11.127 Z2.135 </boundaryPoint>)
(<edge> outer )
;M108 R18.0
G1 X18.27 Y5.84 Z2.13 F3300.0
G1 X18.96 Y5.76 Z2.13 F3300.0
G1 X18.78 Y11.34 Z2.13 F3300.0
G1 X22.39 Y11.76 Z2.13 F3300.0
G1 X20.2 Y11.33 Z2.13 F3300.0
G1 F1200.0
G1 E6.902
G1 F3300.0
M101
G1 X20.2 Y11.33 Z2.13 F1080.0 E6.903
G1 X22.2 Y11.33 Z2.13 F1080.0 E7.0
G1 X22.2 Y4.2 Z2.13 F1080.0 E7.348
G1 X22.6 Y4.2 Z2.13 F1080.0 E7.368
G1 X22.6 Y11.33 Z2.13 F1080.0 E7.716
G1 X24.6 Y11.33 Z2.13 F1080.0 E7.814
G1 X24.6 Y11.88 Z2.13 F1080.0 E7.841
G1 X20.2 Y11.88 Z2.13 F1080.0 E8.055
G1 X20.2 Y11.33 Z2.13 F1080.0 E8.082
G1 F1200.0
G1 E7.082
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X22.195 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X22.596 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X22.596 Y11.327 Z2.135 </infillPoint>)
(<infillPoint> X24.598 Y11.327 Z2.135 </infillPoint>)
(<infillPoint> X24.598 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X20.2 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X20.2 Y11.327 Z2.135 </infillPoint>)
(<infillPoint> X22.195 Y11.327 Z2.135 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X30.58 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X30.58 Y4.954 Z2.135 </boundaryPoint>)
(<boundaryPoint> X26.401 Y4.954 Z2.135 </boundaryPoint>)
(<boundaryPoint> X26.401 Y7.704 Z2.135 </boundaryPoint>)
(<boundaryPoint> X30.167 Y7.704 Z2.135 </boundaryPoint>)
(<boundaryPoint> X30.167 Y8.653 Z2.135 </boundaryPoint>)
(<boundaryPoint> X26.401 Y8.653 Z2.135 </boundaryPoint>)
(<boundaryPoint> X26.401 Y11.127 Z2.135 </boundaryPoint>)
(<boundaryPoint> X30.422 Y11.127 Z2.135 </boundaryPoint>)
(<boundaryPoint> X30.422 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X25.5 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X25.5 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X26.411 Y4.029 Z2.135 </boundaryPoint>)
(<edge> outer )
G1 X22.43 Y11.87 Z2.13 F3300.0
G1 X27.9 Y11.57 Z2.13 F3300.0
G1 X25.7 Y11.33 Z2.13 F3300.0
G1 F1200.0
G1 E8.082
G1 F3300.0
M101
G1 X25.7 Y11.33 Z2.13 F1080.0 E8.082
G1 X25.7 Y4.21 Z2.13 F1080.0 E8.43
G1 X26.41 Y4.23 Z2.13 F1080.0 E8.465
G1 X30.38 Y4.2 Z2.13 F1080.0 E8.659
G1 X30.38 Y4.75 Z2.13 F1080.0 E8.686
G1 X26.2 Y4.75 Z2.13 F1080.0 E8.89
G1 X26.2 Y7.9 Z2.13 F1080.0 E9.044
G1 X29.97 Y7.9 Z2.13 F1080.0 E9.228
G1 X29.97 Y8.45 Z2.13 F1080.0 E9.255
G1 X26.2 Y8.45 Z2.13 F1080.0 E9.438
G1 X26.2 Y11.33 Z2.13 F1080.0 E9.579
G1 X30.22 Y11.33 Z2.13 F1080.0 E9.775
G1 X30.22 Y11.88 Z2.13 F1080.0 E9.802
G1 X25.7 Y11.88 Z2.13 F1080.0 E10.023
G1 X25.7 Y11.33 Z2.13 F1080.0 E10.05
G1 F1200.0
G1 E9.05
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X30.38 Y4.201 Z2.135 </infillPoint>)
(<infillPoint> X30.38 Y4.754 Z2.135 </infillPoint>)
(<infillPoint> X26.201 Y4.754 Z2.135 </infillPoint>)
(<infillPoint> X26.201 Y7.904 Z2.135 </infillPoint>)
(<infillPoint> X29.967 Y7.904 Z2.135 </infillPoint>)
(<infillPoint> X29.967 Y8.453 Z2.135 </infillPoint>)
(<infillPoint> X26.201 Y8.453 Z2.135 </infillPoint>)
(<infillPoint> X26.201 Y11.327 Z2.135 </infillPoint>)
(<infillPoint> X30.222 Y11.327 Z2.135 </infillPoint>)
(<infillPoint> X30.222 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X25.7 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X25.7 Y4.206 Z2.135 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X31.763 Y7.589 Z2.135 </boundaryPoint>)
(<boundaryPoint> X33.072 Y7.55 Z2.135 </boundaryPoint>)
(<boundaryPoint> X33.42 Y7.335 Z2.135 </boundaryPoint>)
(<boundaryPoint> X33.808 Y6.795 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.121 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.72 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.931 Y4.328 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.078 Y6.2 Z2.135 </boundaryPoint>)
(<boundaryPoint> X34.447 Y7.272 Z2.135 </boundaryPoint>)
(<boundaryPoint> X33.994 Y7.674 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.211 Y8.429 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.608 Y9.876 Z2.135 </boundaryPoint>)
(<boundaryPoint> X35.369 Y11.094 Z2.135 </boundaryPoint>)
(<boundaryPoint> X34.728 Y11.863 Z2.135 </boundaryPoint>)
(<boundaryPoint> X33.556 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X31.0 Y12.081 Z2.135 </boundaryPoint>)
(<boundaryPoint> X31.0 Y4.0 Z2.135 </boundaryPoint>)
(<boundaryPoint> X31.763 Y4.0 Z2.135 </boundaryPoint>)
(<edge> outer )
G1 X28.06 Y11.92 Z2.13 F3300.0
G1 X33.4 Y11.54 Z2.13 F3300.0
G1 X31.2 Y11.33 Z2.13 F3300.0
G1 F1200.0
G1 E10.05
G1 F3300.0
M101
G1 X31.2 Y11.33 Z2.13 F1080.0 E10.05
G1 X31.2 Y4.2 Z2.13 F1080.0 E10.398
G1 X31.56 Y4.2 Z2.13 F1080.0 E10.416
G1 X31.56 Y7.79 Z2.13 F1080.0 E10.592
G1 X33.13 Y7.75 Z2.13 F1080.0 E10.668
G1 X33.56 Y7.48 Z2.13 F1080.0 E10.693
G1 X33.98 Y6.9 Z2.13 F1080.0 E10.728
G1 X35.25 Y4.2 Z2.13 F1080.0 E10.874
G1 X35.61 Y4.2 Z2.13 F1080.0 E10.891
G1 X35.7 Y4.34 Z2.13 F1080.0 E10.9
G1 X34.9 Y6.11 Z2.13 F1080.0 E10.994
G1 X34.29 Y7.15 Z2.13 F1080.0 E11.053
G1 X33.69 Y7.7 Z2.13 F1080.0 E11.093
G1 X35.04 Y8.56 Z2.13 F1080.0 E11.171
G1 X35.4 Y9.88 Z2.13 F1080.0 E11.238
G1 X35.18 Y11.01 Z2.13 F1080.0 E11.294
G1 X34.62 Y11.68 Z2.13 F1080.0 E11.337
G1 X33.54 Y11.88 Z2.13 F1080.0 E11.391
G1 X31.2 Y11.88 Z2.13 F1080.0 E11.505
G1 X31.2 Y11.33 Z2.13 F1080.0 E11.532
G1 F1200.0
G1 E11.532
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X33.587 Y11.188 Z2.135 </boundaryPoint>)
(<boundaryPoint> X34.525 Y10.819 Z2.135 </boundaryPoint>)
(<boundaryPoint> X34.822 Y9.876 Z2.135 </boundaryPoint>)
(<boundaryPoint> X34.669 Y9.151 Z2.135 </boundaryPoint>)
(<boundaryPoint> X34.22 Y8.666 Z2.135 </boundaryPoint>)
(<boundaryPoint> X33.403 Y8.515 Z2.135 </boundaryPoint>)
(<boundaryPoint> X31.763 Y8.515 Z2.135 </boundaryPoint>)
(<boundaryPoint> X31.763 Y11.188 Z2.135 </boundaryPoint>)
(<edge> inner )
G1 X31.56 Y11.38 Z2.13 F3300.0
G1 F1200.0
G1 E11.532
G1 F3300.0
M101
G1 X31.56 Y11.39 Z2.13 F1080.0 E11.532
G1 X33.63 Y11.39 Z2.13 F1080.0 E11.633
G1 X34.69 Y10.97 Z2.13 F1080.0 E11.689
G1 X35.03 Y9.89 Z2.13 F1080.0 E11.744
G1 X34.85 Y9.06 Z2.13 F1080.0 E11.786
G1 X34.32 Y8.48 Z2.13 F1080.0 E11.824
G1 X33.42 Y8.31 Z2.13 F1080.0 E11.868
G1 X31.56 Y8.31 Z2.13 F1080.0 E11.959
G1 X31.56 Y11.38 Z2.13 F1080.0 E12.109
G1 F1200.0
G1 E11.109
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(</nestedRing>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X31.563 Y7.795 Z2.135 </infillPoint>)
(<infillPoint> X33.132 Y7.748 Z2.135 </infillPoint>)
(<infillPoint> X33.559 Y7.484 Z2.135 </infillPoint>)
(<infillPoint> X33.981 Y6.897 Z2.135 </infillPoint>)
(<infillPoint> X35.248 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X35.611 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X35.704 Y4.344 Z2.135 </infillPoint>)
(<infillPoint> X34.9 Y6.108 Z2.135 </infillPoint>)
(<infillPoint> X34.291 Y7.143 Z2.135 </infillPoint>)
(<infillPoint> X33.696 Y7.699 Z2.135 </infillPoint>)
(<infillPoint> X35.039 Y8.558 Z2.135 </infillPoint>)
(<infillPoint> X35.403 Y9.884 Z2.135 </infillPoint>)
(<infillPoint> X35.183 Y11.005 Z2.135 </infillPoint>)
(<infillPoint> X34.621 Y11.68 Z2.135 </infillPoint>)
(<infillPoint> X33.538 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X31.2 Y11.881 Z2.135 </infillPoint>)
(<infillPoint> X31.2 Y4.2 Z2.135 </infillPoint>)
(<infillPoint> X31.563 Y4.2 Z2.135 </infillPoint>)
(</infillBoundary>)
(<infillBoundary>)
(<infillPoint> X33.625 Y11.388 Z2.135 </infillPoint>)
(<infillPoint> X34.687 Y10.97 Z2.135 </infillPoint>)
(<infillPoint> X35.029 Y9.886 Z2.135 </infillPoint>)
(<infillPoint> X34.853 Y9.056 Z2.135 </infillPoint>)
(<infillPoint> X34.322 Y8.481 Z2.135 </infillPoint>)
(<infillPoint> X33.421 Y8.315 Z2.135 </infillPoint>)
(<infillPoint> X31.563 Y8.315 Z2.135 </infillPoint>)
(<infillPoint> X31.563 Y11.388 Z2.135 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
;M108 R20.0
M73 P56 (display progress)
(<layer> 2.405 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X4.357 Y7.809 Z2.405 </boundaryPoint>)
(<boundaryPoint> X7.723 Y7.809 Z2.405 </boundaryPoint>)
(<boundaryPoint> X7.723 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X8.58 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X8.58 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X7.723 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X7.723 Y8.763 Z2.405 </boundaryPoint>)
(<boundaryPoint> X4.357 Y8.763 Z2.405 </boundaryPoint>)
(<boundaryPoint> X4.357 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X3.5 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X3.5 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X4.357 Y4.0 Z2.405 </boundaryPoint>)
(<edge> outer )
G1 X33.4 Y10.11 Z2.4 F3300.0
G1 X28.73 Y12.07 Z2.4 F3300.0
G1 X26.2 Y11.33 Z2.4 F3300.0
G1 X26.3 Y9.22 Z2.4 F3300.0
G1 X24.02 Y11.99 Z2.4 F3300.0
G1 X22.6 Y11.33 Z2.4 F3300.0
G1 X22.8 Y8.43 Z2.4 F3300.0
G1 X18.78 Y8.43 Z2.4 F3300.0
G1 X19.16 Y8.42 Z2.4 F3300.0
G1 X18.37 Y6.2 Z2.4 F3300.0
G1 X18.57 Y5.67 Z2.4 F3300.0
G1 X17.23 Y7.76 Z2.4 F3300.0
G1 X15.82 Y10.24 Z2.4 F3300.0
G1 X15.12 Y10.32 Z2.4 F3300.0
G1 X15.3 Y7.06 Z2.4 F3300.0
G1 X13.24 Y7.29 Z2.4 F3300.0
G1 X13.1 Y5.28 Z2.4 F3300.0
G1 X11.03 Y4.43 Z2.4 F3300.0
G1 X7.78 Y4.43 Z2.4 F3300.0
G1 X7.92 Y8.01 Z2.4 F3300.0
G1 X4.16 Y8.01 Z2.4 F3300.0
G1 X3.7 Y4.51 Z2.4 F3300.0
G1 F1200.0
G1 E12.109
G1 F3300.0
M101
G1 X3.7 Y4.2 Z2.4 F1200.0 E12.124
G1 X4.16 Y4.2 Z2.4 F1200.0 E12.147
G1 X4.16 Y8.01 Z2.4 F1200.0 E12.333
G1 X7.92 Y8.01 Z2.4 F1200.0 E12.516
G1 X7.92 Y4.2 Z2.4 F1200.0 E12.703
G1 X8.38 Y4.2 Z2.4 F1200.0 E12.725
G1 X8.38 Y11.88 Z2.4 F1200.0 E13.1
G1 X7.92 Y11.88 Z2.4 F1200.0 E13.122
G1 X7.92 Y8.56 Z2.4 F1200.0 E13.284
G1 X4.16 Y8.56 Z2.4 F1200.0 E13.468
G1 X4.16 Y11.88 Z2.4 F1200.0 E13.63
G1 X3.7 Y11.88 Z2.4 F1200.0 E13.653
G1 X3.7 Y4.51 Z2.4 F1200.0 E14.013
G1 F1200.0
G1 E13.013
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X4.157 Y8.009 Z2.405 </infillPoint>)
(<infillPoint> X7.923 Y8.009 Z2.405 </infillPoint>)
(<infillPoint> X7.923 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X8.38 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X8.38 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X7.923 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X7.923 Y8.563 Z2.405 </infillPoint>)
(<infillPoint> X4.157 Y8.563 Z2.405 </infillPoint>)
(<infillPoint> X4.157 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X3.7 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X3.7 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X4.157 Y4.2 Z2.405 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X10.071 Y4.392 Z2.405 </boundaryPoint>)
(<boundaryPoint> X11.556 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X13.065 Y4.45 Z2.405 </boundaryPoint>)
(<boundaryPoint> X13.86 Y5.615 Z2.405 </boundaryPoint>)
(<boundaryPoint> X14.08 Y7.55 Z2.405 </boundaryPoint>)
(<boundaryPoint> X14.08 Y12.219 Z2.405 </boundaryPoint>)
(<boundaryPoint> X13.226 Y12.219 Z2.405 </boundaryPoint>)
(<boundaryPoint> X13.226 Y7.556 Z2.405 </boundaryPoint>)
(<boundaryPoint> X12.825 Y5.5 Z2.405 </boundaryPoint>)
(<boundaryPoint> X11.481 Y4.965 Z2.405 </boundaryPoint>)
(<boundaryPoint> X10.549 Y5.235 Z2.405 </boundaryPoint>)
(<boundaryPoint> X10.011 Y6.004 Z2.405 </boundaryPoint>)
(<boundaryPoint> X9.855 Y7.556 Z2.405 </boundaryPoint>)
(<boundaryPoint> X9.855 Y12.219 Z2.405 </boundaryPoint>)
(<boundaryPoint> X9.0 Y12.219 Z2.405 </boundaryPoint>)
(<boundaryPoint> X9.0 Y7.55 Z2.405 </boundaryPoint>)
(<boundaryPoint> X9.247 Y5.524 Z2.405 </boundaryPoint>)
(<edge> outer )
G1 X4.16 Y8.01 Z2.4 F3300.0
G1 X7.92 Y8.01 Z2.4 F3300.0
G1 X7.78 Y5.86 Z2.4 F3300.0
G1 X11.0 Y4.67 Z2.4 F3300.0
G1 X9.4 Y5.91 Z2.4 F3300.0
G1 F1200.0
G1 E14.013
G1 F3300.0
M101
G1 X9.44 Y5.6 Z2.4 F1200.0 E14.028
G1 X10.19 Y4.57 Z2.4 F1200.0 E14.09
G1 X11.55 Y4.21 Z2.4 F1200.0 E14.159
G1 X12.94 Y4.62 Z2.4 F1200.0 E14.23
G1 X13.67 Y5.69 Z2.4 F1200.0 E14.293
G1 X13.88 Y7.56 Z2.4 F1200.0 E14.385
G1 X13.88 Y12.02 Z2.4 F1200.0 E14.603
G1 X13.43 Y12.02 Z2.4 F1200.0 E14.625
G1 X13.43 Y7.54 Z2.4 F1200.0 E14.844
G1 X13.0 Y5.36 Z2.4 F1200.0 E14.952
G1 X11.49 Y4.75 Z2.4 F1200.0 E15.032
G1 X10.43 Y5.06 Z2.4 F1200.0 E15.086
G1 X9.82 Y5.93 Z2.4 F1200.0 E15.137
G1 X9.65 Y7.55 Z2.4 F1200.0 E15.217
G1 X9.65 Y12.02 Z2.4 F1200.0 E15.435
G1 X9.2 Y12.02 Z2.4 F1200.0 E15.457
G1 X9.2 Y7.56 Z2.4 F1200.0 E15.675
G1 X9.4 Y5.91 Z2.4 F1200.0 E15.756
G1 F1200.0
G1 E14.756
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X10.191 Y4.567 Z2.405 </infillPoint>)
(<infillPoint> X11.553 Y4.208 Z2.405 </infillPoint>)
(<infillPoint> X12.94 Y4.621 Z2.405 </infillPoint>)
(<infillPoint> X13.667 Y5.687 Z2.405 </infillPoint>)
(<infillPoint> X13.88 Y7.561 Z2.405 </infillPoint>)
(<infillPoint> X13.88 Y12.019 Z2.405 </infillPoint>)
(<infillPoint> X13.426 Y12.019 Z2.405 </infillPoint>)
(<infillPoint> X13.426 Y7.537 Z2.405 </infillPoint>)
(<infillPoint> X13.0 Y5.355 Z2.405 </infillPoint>)
(<infillPoint> X11.491 Y4.754 Z2.405 </infillPoint>)
(<infillPoint> X10.426 Y5.063 Z2.405 </infillPoint>)
(<infillPoint> X9.817 Y5.932 Z2.405 </infillPoint>)
(<infillPoint> X9.655 Y7.546 Z2.405 </infillPoint>)
(<infillPoint> X9.655 Y12.019 Z2.405 </infillPoint>)
(<infillPoint> X9.2 Y12.019 Z2.405 </infillPoint>)
(<infillPoint> X9.2 Y7.562 Z2.405 </infillPoint>)
(<infillPoint> X9.439 Y5.6 Z2.405 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X10.33 Y4.93 Z2.4 F3300.0
G1 X12.56 Y4.8 Z2.4 F3300.0
G1 F1200.0
G1 E15.756
G1 F3300.0
M101
G1 X12.37 Y4.8 Z2.4 F2400.0 E15.766
G1 F1200.0
G1 E14.766
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X15.319 Y9.955 Z2.405 </boundaryPoint>)
(<boundaryPoint> X15.357 Y10.061 Z2.405 </boundaryPoint>)
(<boundaryPoint> X15.422 Y10.077 Z2.405 </boundaryPoint>)
(<boundaryPoint> X15.505 Y10.002 Z2.405 </boundaryPoint>)
(<boundaryPoint> X18.705 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X19.581 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X19.581 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X18.762 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X18.762 Y6.132 Z2.405 </boundaryPoint>)
(<boundaryPoint> X18.724 Y6.026 Z2.405 </boundaryPoint>)
(<boundaryPoint> X18.659 Y6.01 Z2.405 </boundaryPoint>)
(<boundaryPoint> X18.576 Y6.085 Z2.405 </boundaryPoint>)
(<boundaryPoint> X15.376 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X14.501 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X14.501 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X15.319 Y4.0 Z2.405 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X12.81 Y5.07 Z2.4 F3300.0
G1 X12.97 Y6.09 Z2.4 F3300.0
G1 X15.3 Y6.09 Z2.4 F3300.0
G1 X14.7 Y5.11 Z2.4 F3300.0
G1 F1200.0
G1 E15.766
G1 F3300.0
M101
G1 X14.7 Y4.8 Z2.4 F1200.0 E15.781
G1 X14.7 Y4.2 Z2.4 F1200.0 E15.81
G1 X15.12 Y4.2 Z2.4 F1200.0 E15.831
G1 X15.12 Y9.99 Z2.4 F1200.0 E16.114
G1 X15.2 Y10.23 Z2.4 F1200.0 E16.126
G1 X15.48 Y10.3 Z2.4 F1200.0 E16.14
G1 X15.66 Y10.13 Z2.4 F1200.0 E16.152
G1 X18.82 Y4.2 Z2.4 F1200.0 E16.48
G1 X19.38 Y4.2 Z2.4 F1200.0 E16.507
G1 X19.38 Y11.88 Z2.4 F1200.0 E16.882
G1 X18.96 Y11.88 Z2.4 F1200.0 E16.903
G1 X18.96 Y6.1 Z2.4 F1200.0 E17.185
G1 X18.88 Y5.86 Z2.4 F1200.0 E17.198
G1 X18.6 Y5.79 Z2.4 F1200.0 E17.211
G1 X18.42 Y5.96 Z2.4 F1200.0 E17.224
G1 X15.26 Y11.88 Z2.4 F1200.0 E17.552
G1 X14.7 Y11.88 Z2.4 F1200.0 E17.579
G1 X14.7 Y5.11 Z2.4 F1200.0 E17.909
G1 F1200.0
G1 E16.909
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X15.119 Y9.99 Z2.405 </infillPoint>)
(<infillPoint> X15.205 Y10.23 Z2.405 </infillPoint>)
(<infillPoint> X15.477 Y10.297 Z2.405 </infillPoint>)
(<infillPoint> X15.665 Y10.127 Z2.405 </infillPoint>)
(<infillPoint> X18.825 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X19.381 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X19.381 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X18.962 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X18.962 Y6.097 Z2.405 </infillPoint>)
(<infillPoint> X18.876 Y5.857 Z2.405 </infillPoint>)
(<infillPoint> X18.604 Y5.79 Z2.405 </infillPoint>)
(<infillPoint> X18.416 Y5.96 Z2.405 </infillPoint>)
(<infillPoint> X15.256 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X14.701 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X14.701 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X15.119 Y4.2 Z2.405 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X14.92 Y5.07 Z2.4 F3300.0
G1 X15.71 Y9.89 Z2.4 F3300.0
G1 X15.51 Y10.42 Z2.4 F3300.0
G1 X18.6 Y5.05 Z2.4 F3300.0
G1 X19.1 Y4.8 Z2.4 F3300.0
G1 F1200.0
G1 E17.909
G1 F3300.0
M101
G1 X18.82 Y4.8 Z2.4 F2400.0 E17.923
G1 X18.61 Y5.2 Z2.4 F2400.0 E17.945
G1 X19.1 Y5.2 Z2.4 F2400.0 E17.969
G1 F1200.0
G1 E16.969
G1 F2400.0
M103
G1 X14.98 Y10.8 Z2.4 F3300.0
G1 F1200.0
G1 E17.969
G1 F3300.0
M101
G1 X15.52 Y10.8 Z2.4 F2400.0 E17.995
G1 X15.3 Y11.2 Z2.4 F2400.0 E18.017
G1 X14.98 Y11.2 Z2.4 F2400.0 E18.033
G1 F1200.0
G1 E17.033
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X21.995 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X22.796 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X22.796 Y11.127 Z2.405 </boundaryPoint>)
(<boundaryPoint> X24.798 Y11.127 Z2.405 </boundaryPoint>)
(<boundaryPoint> X24.798 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X20.0 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X20.0 Y11.127 Z2.405 </boundaryPoint>)
(<boundaryPoint> X21.995 Y11.127 Z2.405 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X18.27 Y5.84 Z2.4 F3300.0
G1 X18.96 Y5.76 Z2.4 F3300.0
G1 X18.78 Y11.62 Z2.4 F3300.0
G1 X22.4 Y11.62 Z2.4 F3300.0
G1 X20.2 Y11.64 Z2.4 F3300.0
G1 F1200.0
G1 E18.033
G1 F3300.0
M101
G1 X20.2 Y11.33 Z2.4 F1200.0 E18.048
G1 X22.2 Y11.33 Z2.4 F1200.0 E18.146
G1 X22.2 Y4.2 Z2.4 F1200.0 E18.494
G1 X22.6 Y4.2 Z2.4 F1200.0 E18.513
G1 X22.6 Y11.33 Z2.4 F1200.0 E18.861
G1 X24.6 Y11.33 Z2.4 F1200.0 E18.959
G1 X24.6 Y11.88 Z2.4 F1200.0 E18.986
G1 X20.2 Y11.88 Z2.4 F1200.0 E19.201
G1 X20.2 Y11.64 Z2.4 F1200.0 E19.213
G1 F1200.0
G1 E18.213
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X22.195 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X22.596 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X22.596 Y11.327 Z2.405 </infillPoint>)
(<infillPoint> X24.598 Y11.327 Z2.405 </infillPoint>)
(<infillPoint> X24.598 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X20.2 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X20.2 Y11.327 Z2.405 </infillPoint>)
(<infillPoint> X22.195 Y11.327 Z2.405 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X30.58 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X30.58 Y4.954 Z2.405 </boundaryPoint>)
(<boundaryPoint> X26.401 Y4.954 Z2.405 </boundaryPoint>)
(<boundaryPoint> X26.401 Y7.704 Z2.405 </boundaryPoint>)
(<boundaryPoint> X30.167 Y7.704 Z2.405 </boundaryPoint>)
(<boundaryPoint> X30.167 Y8.653 Z2.405 </boundaryPoint>)
(<boundaryPoint> X26.401 Y8.653 Z2.405 </boundaryPoint>)
(<boundaryPoint> X26.401 Y11.127 Z2.405 </boundaryPoint>)
(<boundaryPoint> X30.422 Y11.127 Z2.405 </boundaryPoint>)
(<boundaryPoint> X30.422 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X25.5 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X25.5 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X26.411 Y4.029 Z2.405 </boundaryPoint>)
(<edge> outer )
G1 X22.4 Y11.64 Z2.4 F3300.0
G1 X27.9 Y11.64 Z2.4 F3300.0
G1 X25.7 Y11.64 Z2.4 F3300.0
G1 F1200.0
G1 E19.213
G1 F3300.0
M101
G1 X25.7 Y11.33 Z2.4 F1200.0 E19.228
G1 X25.7 Y4.21 Z2.4 F1200.0 E19.576
G1 X26.41 Y4.23 Z2.4 F1200.0 E19.611
G1 X30.38 Y4.2 Z2.4 F1200.0 E19.805
G1 X30.38 Y4.75 Z2.4 F1200.0 E19.832
G1 X26.2 Y4.75 Z2.4 F1200.0 E20.036
G1 X26.2 Y7.9 Z2.4 F1200.0 E20.189
G1 X29.97 Y7.9 Z2.4 F1200.0 E20.373
G1 X29.97 Y8.45 Z2.4 F1200.0 E20.4
G1 X26.2 Y8.45 Z2.4 F1200.0 E20.584
G1 X26.2 Y11.33 Z2.4 F1200.0 E20.725
G1 X30.22 Y11.33 Z2.4 F1200.0 E20.921
G1 X30.22 Y11.88 Z2.4 F1200.0 E20.948
G1 X25.7 Y11.88 Z2.4 F1200.0 E21.169
G1 X25.7 Y11.64 Z2.4 F1200.0 E21.181
G1 F1200.0
G1 E20.181
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X30.38 Y4.201 Z2.405 </infillPoint>)
(<infillPoint> X30.38 Y4.754 Z2.405 </infillPoint>)
(<infillPoint> X26.201 Y4.754 Z2.405 </infillPoint>)
(<infillPoint> X26.201 Y7.904 Z2.405 </infillPoint>)
(<infillPoint> X29.967 Y7.904 Z2.405 </infillPoint>)
(<infillPoint> X29.967 Y8.453 Z2.405 </infillPoint>)
(<infillPoint> X26.201 Y8.453 Z2.405 </infillPoint>)
(<infillPoint> X26.201 Y11.327 Z2.405 </infillPoint>)
(<infillPoint> X30.222 Y11.327 Z2.405 </infillPoint>)
(<infillPoint> X30.222 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X25.7 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X25.7 Y4.206 Z2.405 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X31.763 Y7.589 Z2.405 </boundaryPoint>)
(<boundaryPoint> X33.072 Y7.55 Z2.405 </boundaryPoint>)
(<boundaryPoint> X33.42 Y7.335 Z2.405 </boundaryPoint>)
(<boundaryPoint> X33.808 Y6.795 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.121 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.72 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.931 Y4.328 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.078 Y6.2 Z2.405 </boundaryPoint>)
(<boundaryPoint> X34.447 Y7.272 Z2.405 </boundaryPoint>)
(<boundaryPoint> X33.994 Y7.674 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.211 Y8.429 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.608 Y9.876 Z2.405 </boundaryPoint>)
(<boundaryPoint> X35.369 Y11.094 Z2.405 </boundaryPoint>)
(<boundaryPoint> X34.728 Y11.863 Z2.405 </boundaryPoint>)
(<boundaryPoint> X33.556 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X31.0 Y12.081 Z2.405 </boundaryPoint>)
(<boundaryPoint> X31.0 Y4.0 Z2.405 </boundaryPoint>)
(<boundaryPoint> X31.763 Y4.0 Z2.405 </boundaryPoint>)
(<edge> outer )
G1 X28.02 Y11.64 Z2.4 F3300.0
G1 X33.4 Y11.64 Z2.4 F3300.0
G1 X31.2 Y11.64 Z2.4 F3300.0
G1 F1200.0
G1 E21.181
G1 F3300.0
M101
G1 X31.2 Y11.33 Z2.4 F1200.0 E21.196
G1 X31.2 Y4.2 Z2.4 F1200.0 E21.544
G1 X31.56 Y4.2 Z2.4 F1200.0 E21.562
G1 X31.56 Y7.79 Z2.4 F1200.0 E21.737
G1 X33.13 Y7.75 Z2.4 F1200.0 E21.814
G1 X33.56 Y7.48 Z2.4 F1200.0 E21.838
G1 X33.98 Y6.9 Z2.4 F1200.0 E21.874
G1 X35.25 Y4.2 Z2.4 F1200.0 E22.019
G1 X35.61 Y4.2 Z2.4 F1200.0 E22.037
G1 X35.7 Y4.34 Z2.4 F1200.0 E22.045
G1 X34.9 Y6.11 Z2.4 F1200.0 E22.14
G1 X34.29 Y7.15 Z2.4 F1200.0 E22.199
G1 X33.69 Y7.7 Z2.4 F1200.0 E22.239
G1 X35.04 Y8.56 Z2.4 F1200.0 E22.317
G1 X35.4 Y9.88 Z2.4 F1200.0 E22.384
G1 X35.18 Y11.01 Z2.4 F1200.0 E22.44
G1 X34.62 Y11.68 Z2.4 F1200.0 E22.483
G1 X33.54 Y11.88 Z2.4 F1200.0 E22.537
G1 X31.2 Y11.88 Z2.4 F1200.0 E22.651
G1 X31.2 Y11.64 Z2.4 F1200.0 E22.663
G1 F1200.0
G1 E22.663
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X33.587 Y11.188 Z2.405 </boundaryPoint>)
(<boundaryPoint> X34.525 Y10.819 Z2.405 </boundaryPoint>)
(<boundaryPoint> X34.822 Y9.876 Z2.405 </boundaryPoint>)
(<boundaryPoint> X34.669 Y9.151 Z2.405 </boundaryPoint>)
(<boundaryPoint> X34.22 Y8.666 Z2.405 </boundaryPoint>)
(<boundaryPoint> X33.403 Y8.515 Z2.405 </boundaryPoint>)
(<boundaryPoint> X31.763 Y8.515 Z2.405 </boundaryPoint>)
(<boundaryPoint> X31.763 Y11.188 Z2.405 </boundaryPoint>)
(<edge> inner )
G1 X31.56 Y11.08 Z2.4 F3300.0
G1 F1200.0
G1 E22.663
G1 F3300.0
M101
G1 X31.56 Y11.39 Z2.4 F1200.0 E22.678
G1 X33.63 Y11.39 Z2.4 F1200.0 E22.778
G1 X34.69 Y10.97 Z2.4 F1200.0 E22.834
G1 X35.03 Y9.89 Z2.4 F1200.0 E22.89
G1 X34.85 Y9.06 Z2.4 F1200.0 E22.931
G1 X34.32 Y8.48 Z2.4 F1200.0 E22.969
G1 X33.42 Y8.31 Z2.4 F1200.0 E23.014
G1 X31.56 Y8.31 Z2.4 F1200.0 E23.105
G1 X31.56 Y11.08 Z2.4 F1200.0 E23.24
G1 F1200.0
G1 E22.24
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(</nestedRing>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X31.563 Y7.795 Z2.405 </infillPoint>)
(<infillPoint> X33.132 Y7.748 Z2.405 </infillPoint>)
(<infillPoint> X33.559 Y7.484 Z2.405 </infillPoint>)
(<infillPoint> X33.981 Y6.897 Z2.405 </infillPoint>)
(<infillPoint> X35.248 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X35.611 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X35.704 Y4.344 Z2.405 </infillPoint>)
(<infillPoint> X34.9 Y6.108 Z2.405 </infillPoint>)
(<infillPoint> X34.291 Y7.143 Z2.405 </infillPoint>)
(<infillPoint> X33.696 Y7.699 Z2.405 </infillPoint>)
(<infillPoint> X35.039 Y8.558 Z2.405 </infillPoint>)
(<infillPoint> X35.403 Y9.884 Z2.405 </infillPoint>)
(<infillPoint> X35.183 Y11.005 Z2.405 </infillPoint>)
(<infillPoint> X34.621 Y11.68 Z2.405 </infillPoint>)
(<infillPoint> X33.538 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X31.2 Y11.881 Z2.405 </infillPoint>)
(<infillPoint> X31.2 Y4.2 Z2.405 </infillPoint>)
(<infillPoint> X31.563 Y4.2 Z2.405 </infillPoint>)
(</infillBoundary>)
(<infillBoundary>)
(<infillPoint> X33.625 Y11.388 Z2.405 </infillPoint>)
(<infillPoint> X34.687 Y10.97 Z2.405 </infillPoint>)
(<infillPoint> X35.029 Y9.886 Z2.405 </infillPoint>)
(<infillPoint> X34.853 Y9.056 Z2.405 </infillPoint>)
(<infillPoint> X34.322 Y8.481 Z2.405 </infillPoint>)
(<infillPoint> X33.421 Y8.315 Z2.405 </infillPoint>)
(<infillPoint> X31.563 Y8.315 Z2.405 </infillPoint>)
(<infillPoint> X31.563 Y11.388 Z2.405 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<operatingLayerEnd> </operatingLayerEnd>)
(</crafting>)
M104 S0
;M113 S0.0
(******* End.gcode*******)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M109 S0 T1 ( Cool down the build platform )
M104 S0 T1 ( Cool down the Right Extruder )
M104 S0 T1 ( Cool down the Left Extruder )
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
